### ISSUE TITLE
Bug: `avroScalaCustomNamespace` not applied to enum field references

### ISSUE THREAD

**Issue by alexandru** [julianpeeters/sbt-avrohugger#116]
When using `avroScalaCustomNamespace`, generated Scala files are emitted under the remapped package, but references to generated enum types inside records still use the original Avro namespace.

Sample JSON

```json
{ 
  "namespace": "com.example.external.events",
  ...
}
```

`build.sbt`:

```scala
Compile / avroScalaCustomNamespace := Map(
  "com.example.external.events" ->
    "com.example.internal.generated.events"
)
```

Generated enum:

```scala
package com.example.internal.generated.events

object EventType extends Enumeration
```

Generated record field references (what happens):

```scala
eventType: com.example.external.events.EventType.Value
```

This fails with a compilation error because `com.example.external` doesn't exist.

What should happen:

```scala
eventType: com.example.internal.generated.events.EventType.Value
```

## Versions

- sbt-avrohugger 2.17.0
- sbt 1.12.12, 2.0.0

NOTE: this was working fine in sbt-avrohugger version 2.16.3.

**Comment by julianpeeters** [comment]
Thanks very much for the report, and sorry you ran into this! I'll take a closer look into this issue in the next few days.

**Comment by alexandru** [comment]
@julianpeeters hey, no worries, and thanks a lot for your work!

**Comment by alexandru** [comment]
The issue appears to also reproduce with `2.16.5`. This may be an issue with the [treehugger](https://github.com/eed3si9n/treehugger/) update.

**Comment by julianpeeters** [comment]
Aha, it was a casualty of some changes to the handling of imports.

I believe this is fixed now, could you give [v2.17.1](https://github.com/julianpeeters/sbt-avrohugger/releases/tag/v2.17.1) a try?
